name: Auto-merge

on:
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Shard CI'

jobs:
  automerge:
    uses: stephendolan/lucky_jumpstart/.github/workflows/automerge.yml@v1.0.0
