name: Auto Merge Dependency Updates

on:
  pull_request:
    branches:
      - 'dependabot/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
