name: Deploy documentation

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0

      - name: "Generate docs"
        run: crystal docs --project-name=Pundit --project-version=${GITHUB_REF##*/}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
